# Generated by Django 5.1.4 on 2025-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinstance',
            name='qgis_project_file',
            field=models.FileField(blank=True, help_text='Path to the .qgz file for this instance.', null=True, upload_to='project_files/'),
        ),
    ]
