# Generated by Django 5.1.4 on 2025-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0002_projectinstance_qgis_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinstance',
            name='qgis_project_file',
        ),
        migrations.AddField(
            model_name='projectinstance',
            name='qgis_folder_path',
            field=models.CharField(blank=True, help_text='Path (relative to MEDIA_ROOT) for the project folder.', max_length=500, null=True),
        ),
    ]
