# Generated by Django 5.1.4 on 2025-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0003_remove_projectinstance_qgis_project_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.SlugField(blank=True, help_text='Unique ID for participants to join.', unique=True),
        ),
    ]
