# Generated by Django 5.1.4 on 2025-01-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0004_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.SlugField(blank=True, help_text='Unique ID for participants to join. Leave empty to let auto-generate.', unique=True),
        ),
    ]
