# Generated by Django 5.1.4 on 2025-02-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0005_alter_project_project_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestGeometry',
        ),
    ]
