# Generated by Django 5.1.4 on 2025-03-10 20:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0006_delete_testgeometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Approximate center location of this project.', null=True, srid=4326),
        ),
    ]
