# Generated by Django 5.1.4 on 2025-03-15 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0007_project_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInstanceUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_folder', models.CharField(help_text='Path relative to MEDIA_ROOT where the upload is stored.', max_length=500)),
                ('project_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='field_manager.projectinstance')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
