# Generated by Django 5.1.4 on 2025-03-16 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0008_projectinstanceuploadrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinstanceuploadrecord',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Project Instance Upload Record', 'verbose_name_plural': 'Project Instances Upload Records'},
        ),
        migrations.AlterField(
            model_name='projectinstanceuploadrecord',
            name='upload_folder',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='ProjectInstanceGeoJSONLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255)),
                ('geojson_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geojson_layers', to='field_manager.projectinstanceuploadrecord')),
            ],
            options={
                'verbose_name': 'Project Instance GeoJSON Layer',
                'verbose_name_plural': 'Project Instances GeoJSON Layers',
                'ordering': ['created_at'],
            },
        ),
    ]
